### PR TITLE
Verification workflow fixes

### LINKED ISSUE #6: Complete authorization tests

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Also added initial tests for the verification workflow so this should fix #6.

I'm specially not sure about:

* The change in the form to allow `nil` for the terms and conditions checkbox. I allowed `nil` because the checkbox is hidden in the view conditionally on the existance of the terms and conditions page.
* The change in the date format. Until I changed it, the date would keep being sent as `nil`. I can investigate further, since this is not reproducible in the tests, and that's weird.

### CODE REVIEW

File: app/forms/decidim/census_connector/verifications/census/verification_handler.rb [hunk 1]
```diff
@@ -11,7 +11,7 @@ class VerificationHandler < CensusHandler
 
           validates :document_file1, presence: true
           validates :document_file2, presence: true, if: :require_document_file2?
-          validates :tos_agreement, allow_nil: false, acceptance: true
+          validates :tos_agreement, allow_nil: true, acceptance: true
```
Comment (leio10) [inline app/forms/decidim/census_connector/verifications/census/verification_handler.rb:14]: Why this? What are the effects of the `allow_nil` here?

**Review by leio10 — APPROVED** [review]
:heart:

File: app/forms/decidim/census_connector/verifications/census/verification_handler.rb (hunk 1 above)
Comment (deivid-rodriguez) [reply app/forms/decidim/census_connector/verifications/census/verification_handler.rb:14]: I explained this in the PR description.

Comment (deivid-rodriguez) [reply app/forms/decidim/census_connector/verifications/census/verification_handler.rb:14]: To further elaborate, without this, the document verification step will fail and give no clue about why. The alternative could be to raise if there's no terms and conditions page for verifications, instead of conditionally render the checbox?

Comment (deivid-rodriguez) [reply app/forms/decidim/census_connector/verifications/census/verification_handler.rb]: To further elaborate, without this, the document verification step will fail and give no clue about it. The alternative could be to raise if there's no terms and conditions page for verifications, instead of conditionally render the checbox?

Comment (leio10) [reply app/forms/decidim/census_connector/verifications/census/verification_handler.rb:14]: :see_no_evil: sorry, it's ok this way

Comment (deivid-rodriguez) [reply app/forms/decidim/census_connector/verifications/census/verification_handler.rb:14]: No problem 😉
